name: Babyschwimmen Gehrden

lang: de_DE
     
plugins:
  - jekyll-feed
  #- jekyll-sitemap
  - jekyll-seo-tag
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown 
